begin;

alter table if exists public.restaurants
  add column if not exists total_tables integer not null default 10;

update public.restaurants
set total_tables = 10
where total_tables is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'restaurants_total_tables_check'
  ) then
    alter table public.restaurants
      add constraint restaurants_total_tables_check
      check (total_tables > 0 and total_tables <= 999);
  end if;
end $$;

create table if not exists public.restaurant_slot_configs (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  day_of_week smallint not null,
  slot_time time not null,
  max_tables integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'restaurant_slot_configs_day_of_week_check'
  ) then
    alter table public.restaurant_slot_configs
      add constraint restaurant_slot_configs_day_of_week_check
      check (day_of_week >= 0 and day_of_week <= 6);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'restaurant_slot_configs_max_tables_check'
  ) then
    alter table public.restaurant_slot_configs
      add constraint restaurant_slot_configs_max_tables_check
      check (max_tables > 0 and max_tables <= 999);
  end if;
end $$;

create unique index if not exists restaurant_slot_configs_unique_slot_idx
  on public.restaurant_slot_configs (restaurant_id, day_of_week, slot_time);

create index if not exists restaurant_slot_configs_restaurant_day_idx
  on public.restaurant_slot_configs (restaurant_id, day_of_week, is_active, slot_time);

create or replace function public.set_restaurant_slot_configs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_restaurant_slot_configs_updated_at
  on public.restaurant_slot_configs;

create trigger trg_restaurant_slot_configs_updated_at
before update on public.restaurant_slot_configs
for each row
execute function public.set_restaurant_slot_configs_updated_at();

alter table public.restaurant_slot_configs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_slot_configs'
      and policyname = 'restaurant_slot_configs_select_owner'
  ) then
    create policy restaurant_slot_configs_select_owner
      on public.restaurant_slot_configs
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.restaurants r
          where r.id = restaurant_slot_configs.restaurant_id
            and r.owner_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_slot_configs'
      and policyname = 'restaurant_slot_configs_insert_owner'
  ) then
    create policy restaurant_slot_configs_insert_owner
      on public.restaurant_slot_configs
      for insert
      to authenticated
      with check (
        exists (
          select 1
          from public.restaurants r
          where r.id = restaurant_slot_configs.restaurant_id
            and r.owner_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_slot_configs'
      and policyname = 'restaurant_slot_configs_update_owner'
  ) then
    create policy restaurant_slot_configs_update_owner
      on public.restaurant_slot_configs
      for update
      to authenticated
      using (
        exists (
          select 1
          from public.restaurants r
          where r.id = restaurant_slot_configs.restaurant_id
            and r.owner_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1
          from public.restaurants r
          where r.id = restaurant_slot_configs.restaurant_id
            and r.owner_id = auth.uid()
        )
      );
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'restaurant_slot_configs'
      and policyname = 'restaurant_slot_configs_delete_owner'
  ) then
    create policy restaurant_slot_configs_delete_owner
      on public.restaurant_slot_configs
      for delete
      to authenticated
      using (
        exists (
          select 1
          from public.restaurants r
          where r.id = restaurant_slot_configs.restaurant_id
            and r.owner_id = auth.uid()
        )
      );
  end if;
end $$;

alter table if exists public.reservations
  add column if not exists reviewed_by uuid,
  add column if not exists reviewed_at timestamptz,
  add column if not exists decline_reason text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reservations_reviewed_by_fkey'
  ) then
    alter table public.reservations
      add constraint reservations_reviewed_by_fkey
      foreign key (reviewed_by)
      references auth.users(id)
      on delete set null;
  end if;
end $$;

create index if not exists reservations_restaurant_status_date_idx
  on public.reservations (restaurant_id, status, date, time);

create index if not exists reservations_reviewed_by_idx
  on public.reservations (reviewed_by);

commit;
